services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - pgsql
    mysql:
        image: 'mysql:8.4'
        ports:
            - '${FORWARD_MYSQL_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PRIMARY_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_PRIMARY_DATABASE}'
            MYSQL_USER: '${DB_PRIMARY_USERNAME}'
            MYSQL_PASSWORD: '${DB_PRIMARY_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './database/schema/mysql-init.sql:/docker-entrypoint-initdb.d/10-create-databases.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PRIMARY_PASSWORD}'
            retries: 3
            timeout: 5s
    pgsql:
        image: 'postgres:18-alpine'
        ports:
            - '${FORWARD_PGSQL_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PRIMARY_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_PRIMARY_DATABASE}'
            POSTGRES_USER: '${DB_PRIMARY_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PRIMARY_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './database/schema/pgsql-init.sql:/docker-entrypoint-initdb.d/10-create-databases.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_PRIMARY_DATABASE}'
                - '-U'
                - '${DB_PRIMARY_USERNAME}'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-pgsql:
        driver: local
